on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: gitupdate
      run: |
        cd /home/ubuntu/mydemo/cicd
        ls -l 
        git pull 
        
